### ISSUE TITLE
Не выполняется команда vagrant up --provider virtualbox

### ISSUE THREAD

**Issue by alexvenga** [Gurukami/dockrant#1]
$ vagrant up --provider virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater]   found entry for: 10.0.0.2 gurukami.local
==> default: [vagrant-hostsupdater]   found entry for: 10.0.0.2 sandbox.local
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: shell...
    default: Running: /var/folders/y1/gq_ywhfn1wg2jd3wmd0v22h40000gn/T/vagrant-shell20161115-3396-5121bi.sh
==> default: mongo uses an image, skipping
==> default: redis uses an image, skipping
==> default: mysql uses an image, skipping
==> default: php56 uses an image, skipping
==> default: php uses an image, skipping
==> default: nginx uses an image, skipping
==> default: Couldn't connect to Docker daemon. You might need to install Docker:
==> default: 
==> default: https://docs.docker.com/engine/installation/
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what

Запускаю на мак ос сиерра
Приложения из списка установлены, Docker в трее активен, пытаюсь выполнять из консоли обычной и из консоли которую запускает докер тулбокс

**Comment by alexvenga** [comment]
Оказалось надо ещё и на саму виртуалку докер ставить)))

**Comment by Nerufa** [comment]
@AlexVenga при запуске vagrant up --provider virtualbox он должен сам установить докер на виртуалке

в инструкциях vagrant это прописано config.vm.provision :docker
